### ISSUE TITLE
Used DefaultBindableLayoutBuilder get exception when scroll the listView

### ISSUE THREAD

**Issue by henr** [mrmans0n/smart-adapters#15]
@mrmans0n the exception occur when I scroll the listView.something wrong in my code?
my code:

```
SmartAdapter.empty()
                        .map(TodoListItem.class, TodoInPreogressListHeader.class)
                        .map(TodoListItem.class, TodoInProgressListItemView.class)
                        .builder(new DefaultBindableLayoutBuilder() {
                            @Override
                            public Class<? extends BindableLayout> viewType(@NonNull Object item, int position, @NonNull Mapper mapper) {
                                if (item instanceof TodoListItem) {
                                    TodoListItem todoItem = (TodoListItem) item;
                                    if (todoItem.todo == null) {
                                        return TodoInPreogressListHeader.class;
                                    } else {
                                        return TodoInProgressListItemView.class;
                                    }
                                } else {
                                    return super.viewType(item, position, mapper);
                                }
                            }
                        })
                        .into(viewHolder.todoList)
```

the exception:

```
java.lang.ArrayIndexOutOfBoundsException: length=2; index=1521438901
            at android.widget.AbsListView$RecycleBin.addScrapView(AbsListView.java:6437)
            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4989)
            at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4193)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:524)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mrmans0n** [comment]
That code looks correct. I would be looking for your error wherever you are adding stuff to the adapter.

**Comment by ApofisXII** [comment]
I have the same problem

**Comment by mrmans0n** [comment]
I think adding this to the anonymous class would help.

> ```
> @Override
> public boolean allowsMultimapping() {
>     return true;
> }
> ```

 As that method returning true is needed if you are using the same class for multiple views.

**Comment by ApofisXII** [comment]
I wrote a reply on the open issue, this is necessary, but won't help to fix it.
