### ISSUE TITLE
I used to proguard ,app crash  

### ISSUE THREAD

**Issue by ipetu** [mrmans0n/smart-adapters#22]
i  proguard-rules.pro  file  writer 

   -keep class io.nlopez.smartadapters.*\* { _; }
   -dontwarn io.nlopez.smartadapters._*

crash log:

java.lang.RuntimeException: Something went wrong creating the views. Please review your BindableLayout implementation.
                                                       at io.nlopez.smartadapters.builders.DefaultBindableLayoutBuilder.build(DefaultBindableLayoutBuilder.java:32)
                                                       at io.nlopez.smartadapters.adapters.RecyclerMultiAdapter.onCreateViewHolder(RecyclerMultiAdapter.java:114)
                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)

can you help me~ think you~

**Comment by ipetu** [comment]
I solved the problem:
   proguard  usage.txt  remove my item view 
Solution to the problem:
-keep class _**.itemView._*{ *;}

**Comment by mkaarthick** [comment]
@dainixiao It didn't work for me. Still crashing with proguard
