### ISSUE TITLE
proguard issue

### ISSUE THREAD

**Issue by mkaarthick** [mrmans0n/smart-adapters#24]
In proguard mode, its throwing error

`Something went wrong creating the views. Please review your BindableLayout implementation.
                                                       at io.nlopez.smartadapters.builders.DefaultBindableLayoutBuilder.build(Unknown Source)
                                                       at io.nlopez.smartadapters.adapters.RecyclerMultiAdapter.onCreateViewHolder(Unknown Source)
                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(Unknown Source)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)`

Folllowed this [https://github.com/mrmans0n/smart-adapters/issues/22](url) link and it didn't work out.

Proguard file:

`-keep class io.nlopez.smartadapters.*\* { *; }

-dontwarn io.nlopez.smartadapters.*

-keep class *_.itemView._{ *;}`

**Comment by mrmans0n** [comment]
Is the last line matching your directory where you put your row views? That
is not all package from the library, that should match your project package
where your custom views are

**Comment by mkaarthick** [comment]
In my case `IndexView` is the row items class and the package is `com.msf.tablet.list`.
modified proguard file as
`-keep public class com.msf.ket.tablet.list.IndexView`
Is this correct?

**Comment by dainixiao** [comment]
-keep class com.msf.ket.tablet.list.*{ *;}  try it

**Comment by ipetu** [comment]
##smartAdapter
-keep class io.nlopez.smartadapters.*\* { _; }
-dontwarn io.nlopez.smartadapters._*
#
-keep class com.msf.ket.tablet.list.**{ *;}
#
-dontwarn com.msf.ket.tablet.list. \*   *

#
